// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlhxgxdccupvymptbbsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaHhneGRjY3VwdnltcHRiYnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTI4MzksImV4cCI6MjA3MTQyODgzOX0.L6hODpy88AE8lZfuDtOEManlgDb0JsprIo-DgZM19ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});